pub(super) fn append(doc: &mut String) {
    doc.push_str(
        r#"
#let cover-info-row(label, value) = {
  stack(
    spacing: 2pt,
    section-label[#upper(label)],
    body-note[#value],
    line(length: 100%, stroke: 0.4pt + luma(220)),
  )
}

#let cover-page() = {
  let data = json("summary.json")
  let status-color = if data.overall-status == "pass" {
    rgb(25, 135, 84)
  } else if data.overall-status == "fail" {
    rgb(220, 53, 69)
  } else {
    rgb(108, 117, 125)
  }

  v(6pt)
  grid(
    columns: (1fr, auto),
    gutter: 0pt,
    stack(
      spacing: 6pt,
      text(size: 22pt, weight: "bold", tracking: 1pt)[THORNTON TOMASETTI],
      text(size: 10pt, fill: luma(90), tracking: 0.5pt)[STRUCTURAL ENGINEERING],
    ),
    align(right + top)[
      #block(fill: status-color, radius: 3pt, inset: (x: 12pt, y: 6pt))[
        #text(size: 10pt, weight: "bold", fill: white)[#upper(data.overall-status)]
      ]
    ],
  )

  v(14pt)
  line(length: 100%, stroke: 2pt + black)
  v(20pt)

  text(size: 28pt, weight: "bold")[#project.project-name]
  v(8pt)
  text(size: 14pt, fill: luma(40))[#project.subject]
  v(28pt)

  grid(
    columns: (2.2fr, 1fr),
    gutter: 30pt,

    stack(
      spacing: 8pt,
      cover-info-row("Project Number", project.project-number),
      cover-info-row("Reference", project.reference),
      cover-info-row("Code", data.code),
      cover-info-row("Revision", project.revision),
      cover-info-row("Branch", data.branch),
      cover-info-row("Version", data.version-id),
      cover-info-row("Date", project.date),
      cover-info-row("Engineer", project.engineer),
      cover-info-row("Checker", project.checker),
    ),

    stack(
      spacing: 8pt,
      section-label[CHECKS],
      v(2pt),
      ..data.lines.map(line => {
        let dot-color = if line.status == "pass" {
          rgb(25, 135, 84)
        } else if line.status == "fail" {
          rgb(220, 53, 69)
        } else if line.status == "warn" {
          rgb(255, 193, 7)
        } else {
          luma(160)
        }
        (
          grid(
            columns: (8pt, 1fr, auto),
            gutter: 5pt,
            align: horizon,
            circle(radius: 4pt, fill: dot-color),
            text(size: 8pt)[#line.key],
            text(size: 7pt)[#status-text(line.status)],
          ),
          v(3pt),
        )
      }).flatten(),
    ),
  )

  v(1fr)
  line(length: 100%, stroke: 0.5pt + luma(180))
  v(6pt)
  text(size: 7pt, fill: luma(130))[
    Generated by EtabExtension - Branch: #data.branch - Version: #data.version-id
  ]
}

#let summary-page() = {
  let data = json("summary.json")
  page-title[#project.project-name]
  body-note[#project.subject]
  v(10pt)
  grid(
    columns: (1fr, 1fr),
    gutter: 16pt,
    [
      #stack(
        spacing: 3pt,
        [*Reference:* #project.reference],
        [*Code:* #data.code],
        [*Project No.:* #project.project-number],
        [*Revision:* #project.revision],
        [*Branch / Version:* #data.branch / #data.version-id],
      )
    ],
    [
      #stack(
        spacing: 3pt,
        [*Engineer:* #project.engineer],
        [*Checker:* #project.checker],
        [*Date:* #project.date],
        [*Status:* #status-text(data.overall-status)],
      )
    ],
  )
  v(parse-pt(theme.section-gap))
  page-title[Report Summary]
  v(6pt)
  for line in data.lines [
    - #line.key (#status-text(line.status)) #line.message
  ]
  v(10pt)
  page-title[Checker Summary]
  v(4pt)
  table(
    columns: (1.2fr, 0.55fr, 0.9fr, 0.75fr, 0.75fr, 0.75fr, 0.65fr, 0.65fr, 1.7fr),
    fill: (x, y) => if y == 0 { luma(220) } else { row-fill("", y) },
    align: (x, y) => if x <= 3 or x == 8 { left } else { right },
    table.header(repeat: true,
      ..("Check", "Status", "Case", "Story", "Demand", "Limit", "Util.", "Margin", "Reason / Basis")
        .map(h => table.cell(fill: luma(220))[#h])
    ),
    ..data.checker-rows.map(row => (
      row.check,
      table.cell(align: left)[#status-text(row.status)],
      row.governing-case,
      row.governing-story,
      row.demand,
      row.limit,
      if row.ratio-color-value == none {
        row.utilization
      } else {
        table.cell(
          align: right,
          fill: ratio-fill(row.ratio-color-value, row.ratio-color-scale-kind),
        )[#row.utilization]
      },
      row.margin,
      row.reason,
    )).flatten(),
  )
}

#let scope-limitations-page() = {
  page-title[Scope and Limitations]
  v(parse-pt(theme.section-gap))
  enum(
    [This report is an internal screening/reporting tool generated from ETABS extracted results.],
    [Automated pass/fail status does not replace project-specific engineering judgment.],
    [Assumptions include load-case mapping, tracking-group selection, and material fallbacks where source data is incomplete.],
    [Preliminary checks (pier axial screening) are not full code-design verification.],
    [Final design and sign-off require responsible engineer review.],
  )
}

#let modal-page() = {
  let data = json("modal.json")
  page-title[Modal Participation]
  v(parse-pt(theme.section-gap))
  section-label[Mass participation threshold = #(data.threshold * 100.0)%]
  v(4pt)
  table(
    columns: (0.8fr, 0.9fr, 0.8fr, 0.8fr, 0.8fr, 0.9fr, 0.9fr, 0.9fr, 1fr),
    fill: (x, y) => if y == 0 { luma(220) } else { row-fill(data.annotations.at(y - 1, default: ""), y) },
    align: (x, y) => if x >= 1 { right } else { left },
    repeating-header(
      9,
      ..("Mode", "Period", "UX", "UY", "UZ", "Sum UX", "Sum UY", "Sum UZ", "Highlight")
        .map(h => table.cell(fill: luma(220))[#h])
    ),
    ..range(data.rows.len()).map(i => {
      let row = data.rows.at(i)
      let tag = data.annotations.at(i, default: "")
      let highlight-label = if tag == "ux_threshold" { "UX threshold" }
                            else if tag == "uy_threshold" { "UY threshold" }
                            else if tag == "ux_uy_threshold" { "UX/UY threshold" }
                            else { "" }
      (
        str(row.mode),
        str(calc.round(row.period, digits: 3)),
        str(calc.round(row.ux * 100.0, digits: 1)) + "%",
        str(calc.round(row.uy * 100.0, digits: 1)) + "%",
        str(calc.round(row.uz * 100.0, digits: 1)) + "%",
        str(calc.round(row.sum-ux * 100.0, digits: 1)) + "%",
        str(calc.round(row.sum-uy * 100.0, digits: 1)) + "%",
        str(calc.round(row.sum-uz * 100.0, digits: 1)) + "%",
        highlight-label,
      )
    }).flatten(),
  )
}

#let base-reactions-table(data) = {
  table(
    columns: (1.2fr, 0.9fr, 0.8fr, 0.7fr, 0.9fr, 0.9fr, 0.9fr, 0.9fr, 0.9fr, 0.9fr),
    fill: (x, y) => if y == 0 { luma(220) } else { row-fill("", y) },
    align: (x, y) => if x >= 3 { right } else { left },
    table.header(repeat: true,
      ..("Load Case", "Type", "Step", "No.", "Fx (kip)", "Fy (kip)", "Fz (kip)", "Mx (kip-ft)", "My (kip-ft)", "Mz (kip-ft)")
        .map(h => table.cell(fill: luma(220))[#h])
    ),
    ..data.rows.map(row => (
      row.output-case,
      row.case-type,
      row.step-type,
      if row.step-number == none { "-" } else { str(calc.round(row.step-number, digits: 3)) },
      str(calc.round(row.fx-kip, digits: 2)),
      str(calc.round(row.fy-kip, digits: 2)),
      str(calc.round(row.fz-kip, digits: 2)),
      str(calc.round(row.mx-kip-ft, digits: 2)),
      str(calc.round(row.my-kip-ft, digits: 2)),
      str(calc.round(row.mz-kip-ft, digits: 2)),
    )).flatten(),
  )
}

#let base-reactions-page() = {
  let data = json("base_reactions.json")
  let pass-str = if data.pass { "PASS" } else { "FAIL" }
  page-title[Base Reaction Review]
  v(parse-pt(theme.section-gap))
  let table-body = [#align(top)[
    #section-label[Main review excludes case types Combination, LinModRitz, and Eigen.]
    #v(4pt)
    #base-reactions-table(data)
  ]]
  let chart-body = [#align(center)[
    #ext-figure("images/base_reactions.svg", [Base Reactions Envelope (kip)], parse-in(theme.chart-with-table-normal-h))
    #v(6pt)
    #align(right)[#section-label[Status: #status-text(pass-str) (X ratio #calc.round(data.ratio-x, digits: 3), Y ratio #calc.round(data.ratio-y, digits: 3))]]
  ]]
  chart-table-layout(table-body, chart-body)
}

#let story-forces-page(title, chart1, chart2) = {
  two-charts-page(title, chart1, "Shear (kip)", chart2, "Moment (kip-ft)")
}

#let drift-table(data-node) = {
  table(
    columns: data-node.groups.len() + 2,
    fill: (x, y) => if y == 0 { luma(220) } else { row-fill("", y) },
    align: (x, y) => if x == 0 { left } else { right },
    table.header(repeat: true, [Story], [Limit (ratio)], ..data-node.groups.map(g => [#g (ratio)])),
    ..range(data-node.levels.len()).map(i => {
      let row = data-node.matrix.at(i, default: ())
      (
        data-node.levels.at(i, default: "-"),
        str(calc.round(data-node.allowable-ratio, digits: 3)),
        ..range(data-node.groups.len()).map(j => {
          let value = row.at(j, default: none)
          if value == none { "-" } else { str(calc.round(value, digits: 3)) }
        }),
      )
    }).flatten(),
  )
}

#let drift-dir-page(title, data-node, chart-file) = {
  page-title[#title]
  v(parse-pt(theme.section-gap))
  let pass-str = if data-node.pass { "PASS" } else { "FAIL" }
  let table-body = [#align(top)[
    #section-label[
      Governing: #data-node.governing-story #data-node.governing-direction #data-node.governing-case (#status-text(pass-str))
    ]
    #v(4pt)
    #drift-table(data-node)
  ]]
  let chart-body = [#stack(
    spacing: 0pt,
    align(center)[
      #ext-figure(chart-file, [Drift demand ratio by tracking group], parse-in(theme.chart-with-table-chart-h))
    ],
    v(1fr),
    align(right)[
      #stack(
        spacing: 2pt,
        body-note[Demand ratio: #calc.round(data-node.governing-demand-ratio, digits: 3)],
        body-note[Allowable ratio: #calc.round(data-node.allowable-ratio, digits: 3)],
        body-note[Utilization: #calc.round(data-node.governing-utilization * 100.0, digits: 2)% | Margin: #calc.round(data-node.governing-margin-ratio, digits: 3)],
        body-note[Basis: max drift ratio demand per group/story against allowable ratio.],
        section-label[Status: #status-text(pass-str)],
      )
    ],
  )]
  chart-table-layout(table-body, chart-body, emphasized: true)
}

#let displacement-table(data-node) = {
  table(
    columns: data-node.groups.len() + 3,
    fill: (x, y) => if y == 0 { luma(220) } else { row-fill("", y) },
    align: (x, y) => if x <= 1 { left } else { right },
    table.header(repeat: true, [Story], [Elevation (ft)], [Limit (in)], ..data-node.groups.map(g => [#g (in)])),
    ..range(data-node.levels.len()).map(i => {
      let row = data-node.matrix-in.at(i, default: ())
      (
        data-node.levels.at(i, default: "-"),
        str(calc.round(data-node.level-elevations-ft.at(i, default: 0.0), digits: 2)),
        str(calc.round(data-node.level-limits-in.at(i, default: 0.0), digits: 3)),
        ..range(data-node.groups.len()).map(j => {
          let value = row.at(j, default: none)
          if value == none { "-" } else { str(calc.round(value, digits: 3)) }
        }),
      )
    }).flatten(),
  )
}

#let displacement-dir-page(title, data-node, chart-file) = {
  page-title[#title]
  v(parse-pt(theme.section-gap))
  let pass-str = if data-node.pass { "PASS" } else { "FAIL" }
  let table-body = [#align(top)[
    #section-label[
      Governing: #data-node.governing-story #data-node.governing-direction #data-node.governing-case (#status-text(pass-str))
    ]
    #v(4pt)
    #displacement-table(data-node)
  ]]
  let chart-body = [#stack(
    spacing: 0pt,
    align(center)[
      #ext-figure(chart-file, [Displacement demand by tracking group], parse-in(theme.chart-with-table-chart-h))
    ],
    v(1fr),
    align(right)[
      #stack(
        spacing: 2pt,
        body-note[Demand (in): #calc.round(data-node.governing-utilization * data-node.governing-limit-in, digits: 3)],
        body-note[Limit (in): #calc.round(data-node.governing-limit-in, digits: 3) | Utilization: #calc.round(data-node.governing-utilization * 100.0, digits: 2)% | Margin: #calc.round(data-node.governing-margin * 100.0, digits: 2)%],
        body-note[Basis: per-level limit = level elevation / configured ratio divisor.],
        section-label[Status: #status-text(pass-str)],
      )
    ],
  )]
  chart-table-layout(table-body, chart-body, emphasized: true)
}

#let torsional-dir-page(title, data-node, chart-file) = {
  page-title[#title]
  v(parse-pt(theme.section-gap))
  let pass-str = if data-node.has-type-b { "FAIL" } else { "PASS" }
  if data-node.has-rows {
    section-label[
      Governing story: #data-node.governing-story | Case: #data-node.governing-case | Pair: #data-node.governing-joint-a / #data-node.governing-joint-b | Step: #data-node.governing-step
    ]
    body-note[
      Drift A: #calc.round(data-node.governing-drift-a, digits: 3) | Drift B: #calc.round(data-node.governing-drift-b, digits: 3)
    ]
    body-note[DeltaMax: #calc.round(data-node.governing-delta-max, digits: 3) | DeltaAvg: #calc.round(data-node.governing-delta-avg, digits: 3)]
    box(
      inset: (x: 4pt, y: 2pt),
      radius: 2pt,
      fill: ratio-fill(data-node.governing-ratio-color-value, data-node.governing-ratio-color-scale-kind),
    )[
      #section-label[Ratio: #calc.round(data-node.governing-ratio, digits: 3)]
    ]
    body-note[
      Thresholds: Type A > #calc.round(data-node.type-a-threshold, digits: 2), Type B > #calc.round(data-node.type-b-threshold, digits: 2) | Classification: #data-node.classification
    ]
  } else {
    section-label[#data-node.no-data-note]
    body-note[Thresholds: Type A > #calc.round(data-node.type-a-threshold, digits: 2), Type B > #calc.round(data-node.type-b-threshold, digits: 2) | Classification: #data-node.classification]
  }
  v(4pt)
  let torsion-rows = if data-node.has-rows {
    data-node.rows.map(row => (
      row.story,
      row.case,
      row.joint-a,
      row.joint-b,
      str(row.governing-step),
      str(calc.round(row.drift-a, digits: 3)),
      str(calc.round(row.drift-b, digits: 3)),
      str(calc.round(row.delta-max, digits: 3)),
      str(calc.round(row.delta-avg, digits: 3)),
      ratio-cell(row.ratio-color-value, row.ratio-color-scale-kind),
    )).flatten()
  } else {
    (
      data-node.no-data-note, "", "", "", "", "", "", "", "", "",
    )
  }
  table(
    columns: (1fr, 1fr, 1fr, 1fr, 0.65fr, 0.8fr, 0.8fr, 0.9fr, 0.9fr, 0.8fr),
    fill: (x, y) => if y == 0 { luma(220) } else { row-fill(data-node.annotations.at(y - 1, default: ""), y) },
    align: (x, y) => if x >= 4 { right } else { left },
    table.header(repeat: true,
      ..("Story", "Case", "Joint A", "Joint B", "Step", "Drift A", "Drift B", "DeltaMax", "DeltaAvg", "Ratio")
        .map(h => table.cell(fill: luma(220))[#h])
    ),
    ..torsion-rows,
  )
  v(6pt)
  align(center)[
    #ext-figure(chart-file, [Story governing torsional ratio with 1.2/1.4 thresholds], parse-in(theme.chart-with-table-chart-h))
  ]
  v(4pt)
  align(right)[#section-label[Status: #status-text(pass-str)]]
}
"#,
    );
}
