// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Generic CLI result wrapper
 */
export type CliResult<T> = { success: boolean, error: string | null, timestamp: string, data: T | null, };
