// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VersionIdentifier } from "./VersionIdentifier";

/**
 * Request to compare two versions
 */
export type CompareVersionsRequest = { project_path: string, version1: VersionIdentifier, version2: VersionIdentifier, diff_type: string, };
