// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to create a new branch
 */
export type CreateBranchRequest = { project_path: string, branch_name: string, from_branch: string, from_version: string, description: string | null, };
