// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Individual E2K change
 */
export type E2KChange = { type: string, category: string, description: string, old_value: string | null, new_value: string | null, };
