// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { E2KChange } from "./E2KChange";

/**
 * E2K file comparison result
 */
export type E2KDiffResult = { added: number, removed: number, modified: number, changes: Array<E2KChange>, raw_diff: string, };
