// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * ETABS application status
 */
export type EtabsStatus = { is_running: boolean, version: string | null, current_file: string | null, };
