// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 3D geometry comparison result
 */
export type GeometryDiffResult = { members_added: Array<string>, members_removed: Array<string>, members_modified: Array<string>, total_changes: number, };
