// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to save a version
 */
export type SaveVersionRequest = { project_path: string, branch_name: string, message: string, generate_e2k: boolean, };
