// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Working file status
 */
export type WorkingFileInfo = { exists: boolean, path: string, is_open: boolean, has_unsaved_changes: boolean, source_version: string | null, };
